<MainWindow>:
    BoxLayout:
        orientation: 'vertical'
        spacing: 20
        Label:
            text:"Főmenü"
            font_size:'50sp'
        Button:
            text: "Saját kollázs"
            id: 'btn1'
        Button:
            text: "Demo kollázs"
            id: 'btn2'
        Button:
            text: "Segédlet"
            id: 'btn3'
        Button:
            text: "Kilépés"
            id: 'btn4'